use utf8;
use strict;
use warnings;
use open qw( :encoding(UTF-8) :std );
use Test::More tests => 27;
use Lingua::Stem::UniNE::CS qw( stem );

is stem('zvířatech'), 'zvíř',   'remove -atech';
is stem('zvířatům'),  'zvíř',   'remove -atům';
is stem('dítětem'),   'dít',    'remove -tem from -ětem';
is stem('kterými'),   'kter',   'remove -ými';
is stem('rukama'),    'ruk',    'remove -ama';
is stem('ženami'),    'žen',    'remove -ami';
is stem('zvířata'),   'zvíř',   'remove -ata';
is stem('zvířaty'),   'zvíř',   'remove -aty';
is stem('pánové'),    'pán',    'remove -ové';
is stem('tátovi'),    'tát',    'remove -ovi';
is stem('novinách'),  'novin',  'remove -ách';
is stem('kterých'),   'kter',   'remove -ých';
is stem('řekněte'),   'řekn',   'remove -te from -ěte';
is stem('paměti'),    'pam',    'remove -ti from -ěti';
is stem('systému'),   'syst',   'remove -mu from -ému';
is stem('režimu'),    'reh',    'remove -mu from -imu';
is stem('letech'),    'let',    'remove -ch from -ech';
is stem('jejich'),    'jej',    'remove -ch from -ich';
is stem('dalších'),   'dalš',   'remove -ch from -ích';
is stem('mřížemi'),   'mříh',   'remove -mi from -emi';
is stem('zbraněmi'),  'zbran',  'remove -mi from -ěmi';
is stem('ostatními'), 'ostatn', 'remove -mi from -ími';
is stem('jiného'),    'jin',    'remove -ho from -ého';
note 'no test for: ',           'remove -ho from -iho';
is stem('jejího'),    'jej',    'remove -ho from -ího';

is stem('pracovat'),  'prac',   'remove -ov';
is stem('králův'),    'král',   'remove -ův';
is stem('většina'),   'větš',   'remove -in from -i';
