use strict;
use warnings;
use utf8;
use open qw( :encoding(UTF-8) :std );
use Test::More tests => 27;
use Lingua::Stem::UniNE::CS qw( stem_cs );

is stem_cs('zvířatech'), 'zvíř',   'remove -atech';
is stem_cs('zvířatům'),  'zvíř',   'remove -atům';
is stem_cs('dítětem'),   'dít',    'remove -tem from -ětem';
is stem_cs('kterými'),   'kter',   'remove -ými';
is stem_cs('rukama'),    'ruk',    'remove -ama';
is stem_cs('ženami'),    'žen',    'remove -ami';
is stem_cs('zvířata'),   'zvíř',   'remove -ata';
is stem_cs('zvířaty'),   'zvíř',   'remove -aty';
is stem_cs('pánové'),    'pán',    'remove -ové';
is stem_cs('tátovi'),    'tát',    'remove -ovi';
is stem_cs('novinách'),  'novin',  'remove -ách';
is stem_cs('kterých'),   'kter',   'remove -ých';
is stem_cs('řekněte'),   'řekn',   'remove -te from -ěte';
is stem_cs('paměti'),    'pam',    'remove -ti from -ěti';
is stem_cs('systému'),   'syst',   'remove -mu from -ému';
is stem_cs('režimu'),    'reh',    'remove -mu from -imu';
is stem_cs('letech'),    'let',    'remove -ch from -ech';
is stem_cs('jejich'),    'jej',    'remove -ch from -ich';
is stem_cs('dalších'),   'dalš',   'remove -ch from -ích';
is stem_cs('mřížemi'),   'mříh',   'remove -mi from -emi';
is stem_cs('zbraněmi'),  'zbran',  'remove -mi from -ěmi';
is stem_cs('ostatními'), 'ostatn', 'remove -mi from -ími';
is stem_cs('jiného'),    'jin',    'remove -ho from -ého';
note 'no test for: ',              'remove -ho from -iho';
is stem_cs('jejího'),    'jej',    'remove -ho from -ího';

is stem_cs('pracovat'),  'prac',   'remove -ov';
is stem_cs('králův'),    'král',   'remove -ův';
is stem_cs('většina'),   'větš',   'remove -in from -i';
